[package]
license = "MIT"
name = "mll"
version = "0.1.0"
edition = "2021"
repository = "https://github.com/jackos/mll"
hompage = "https://github.com/jackos/mll"
description = "placeholder for mll library"
readme = "README.md"


[dependencies]
